GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2Nlc3MiLCJleHAiOjE1NDkyNjMzMzQsImlhdCI6MTU0OTI1NjkzNCwibmJmIjoxNTQ5MjU2OTM0LCJqdGkiOiJkYmQxZGM1OS1lYTQ2LTRkMzYtYTQyZi1lYTI3ODI4MDE4OTEiLCJ1c2VybmFtZSI6InRlc3QifQ.neblVC8eTc5kwXl-iji9HNleY46DCmy6QL1F-46AL9rHkPIiHBzL2EfaSkC8w9c3Uqmp8TPu5EgdMOlY4WnClg

###