DELETE http://localhost:8080/plans/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2Nlc3MiLCJleHAiOjE1NDU4MTE2NTAsImlhdCI6MTU0NTgwNTI1MCwibmJmIjoxNTQ1ODA1MjUwLCJqdGkiOiI1ODgxMDY0YS01YjVkLTQwYWQtODQzZC03NGRkMzdmM2I3ZDgiLCJ1c2VybmFtZSI6InRlc3QifQ.eeMngpVPgojsRarb9RO2dtGnkbzcWk-V63w404bVCgNsv43FBOdwBh6owIbTd6gvTHrooUkDqipIyscsjmI2Lw

###